Add match logic and improved options for match
5C-Dziki/FMSim pull request #13
Opened 2024-12-03 11:50 UTC by bartekluc

2024-12-03 11:52 UTC, JanGrzeskowiak requested changes

2024-12-03 11:52 UTC, JanGrzeskowiak commented on FMSim/FMInterface/Actions/Match.cs
> +
Proszę przenieść do odpowiedniej klasy

2024-12-03 11:53 UTC, JanGrzeskowiak commented on FMSim/FMInterface/Actions/Match.cs
> +
Pliku klasy*

2024-12-03 11:53 UTC, MishutkAviation requested changes
As commented, a lot of duplicated classes and methods. Fix pleaaaase

2024-12-03 11:53 UTC, MishutkAviation commented on FMSim/FMInterface/Actions/Match.cs
> +    public class Program
Please change generic class name

2024-12-03 11:53 UTC, MishutkAviation commented on FMSim/FMInterface/Actions/Match.cs
> +namespace FMInterface.Actions
Wrong namespace?

2024-12-10 09:57 UTC, JanGrzeskowiak approved these changes

2024-12-10 10:21 UTC, MishutkAviation approved these changes

2024-12-10 10:21 UTC, merged